services:
  slackfrontend :
    build:
      context: ./client
      dockerfile: Dockerfile.client
    ports:
      - "3000:3000"   
    depends_on:
      - db
  nodebackend:
    build:
      context: ./server
      dockerfile: Dockerfile.server
    ports:
      - "8001:8001"   
    depends_on:
      - db
  db:
    volumes:
      - slack_db:/data/db
    image: mongo:latest
    ports:
      - "27017:27017" 
volumes:
   slack_db: