version: "3.8"
services:
  # mongodb: 
  #   image: "mongo"
  #   volumes:
  #     - data:/data/db
  server:
    build: ./server
    ports:
      - target: 8084
        published: 8084
        protocol: tcp
        mode: host
    volumes:
      - ./server:/app
      - /app/node_modules
    # depends_on:
    #   - mongodb

  client:
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client/src:/app/src
    stdin_open: true
    tty: true
    depends_on:
      - server
volumes:
  data: 